import { defineConfig } from 'tsup'

export default defineConfig({
	entry: [
		'src/index.ts',
		'src/contract.css.ts',
		'src/themes/dark.css.ts',
		'src/themes/light.css.ts',
		'src/global.css.ts',
	],
	format: ['esm', 'cjs'],
	dts: true,
	target: 'es2022',
	sourcemap: true,
	clean: {
		// Don't clean dist/css/ — those are generated by Style Dictionary
		exclude: ['dist/css/**'],
	},
	external: ['@vanilla-extract/css'],
})
